name: huaweistore-dev
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:      
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "###################"
      - run: |
          echo "###################"

  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "###################"
      - run: |
          echo "###################"

