name: amazonstore-dev1
concurrency:
  group: amazonstore-dev1
  cancel-in-progress: true

on: 
  workflow_dispatch:
     inputs:
       force_release:
         description: 'Force release?'
         required: true
         type: boolean
       custom_version:
         description: 'Custom version'
         required: false
         type: string
  push:
    branches:
      - main

jobs:      
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "###################"
      - run: |
          echo "###################"

  test:
    name: test
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "###################"
      - run: |
          echo "###################"

