name: test4
on: 
  workflow_dispatch:
     inputs:
       param1:
         description: 'Param 1'
         required: true
         type: choice
         default: info
         options:
           - info
           - warning
           - debug
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "###################"
          echo '${{ inputs.param1 }}'
